// Mock data for demonstration - Bars à chicha dans la région Île-de-France
export const mockBars = [
  {
    id: 1,
    osm_id: 'demo_1',
    name: 'Black Iris Lounge',
    latitude: 48.9967540,
    longitude: 1.7150009,
    address: '6 & 8 Allée de Chantereine LOT 9',
    city: 'Mantes-la-Jolie',
    postal_code: '78200',
    phone: '+33 1 XX XX XX XX',
    website: '',
    price_range: '€€',
    average_rating: 5.0,
    review_count: 9,
    amenities: {
      wifi: true,
      parking: true,
      terrace: false,
      accessible: true,
      music: true,
      food: true
    },
    opening_hours: 'Lun-Dim: 14h-2h',
    photos: [],
    image: '53c0047a-9fe6-46d8-a85f-b151ad268c96.png',
    description: 'Bar à chicha avec une ambiance conviviale et une large sélection de saveurs.',
    type: 'bar'
  },
  {
    id: 2,
    osm_id: 'demo_2',
    name: 'Le Lounge Oriental',
    latitude: 48.8566,
    longitude: 2.3522,
    address: '123 Rue de Rivoli',
    city: 'Paris',
    postal_code: '75001',
    phone: '+33 1 23 45 67 89',
    website: 'https://example.com',
    price_range: '€€€',
    average_rating: 4.5,
    review_count: 42,
    amenities: {
      wifi: true,
      parking: false,
      terrace: true,
      accessible: true,
      music: true,
      food: true
    },
    opening_hours: 'Lun-Dim: 18h-2h',
    photos: [],
    image: '5e29a997-cd8f-408a-9c88-1c65e5355eab.png',
    description: 'Bar à chicha premium au cœur de Paris avec une décoration orientale authentique.',
    type: 'bar'
  },
  {
    id: 3,
    osm_id: 'demo_3',
    name: 'Shisha Paradise',
    latitude: 48.8738,
    longitude: 2.2950,
    address: '45 Avenue des Champs-Élysées',
    city: 'Paris',
    postal_code: '75008',
    phone: '+33 1 34 56 78 90',
    website: 'https://shisha-paradise.fr',
    price_range: '€€€',
    average_rating: 4.7,
    review_count: 128,
    amenities: {
      wifi: true,
      parking: true,
      terrace: true,
      accessible: true,
      music: true,
      food: true
    },
    opening_hours: 'Lun-Dim: 16h-3h',
    photos: [],
    image: '8f2fc303-4323-45f3-aac9-6ee492c8c2ca.png',
    description: 'Le plus grand lounge à chicha de Paris. Ambiance VIP, DJ tous les soirs.',
    type: 'bar'
  },
  {
    id: 4,
    osm_id: 'demo_4',
    name: 'Café Narguilé',
    latitude: 48.9924,
    longitude: 1.7185,
    address: '15 Rue Nationale',
    city: 'Mantes-la-Jolie',
    postal_code: '78200',
    phone: '+33 1 45 67 89 01',
    website: '',
    price_range: '€',
    average_rating: 4.2,
    review_count: 34,
    amenities: {
      wifi: true,
      parking: false,
      terrace: true,
      accessible: false,
      music: false,
      food: true
    },
    opening_hours: 'Mar-Dim: 15h-23h',
    photos: [],
    image: 'e148ab54-e972-49f1-9882-c0e0d65d17c1.png',
    description: 'Café traditionnel avec chichas et spécialités orientales.',
    type: 'cafe'
  },
  {
    id: 5,
    osm_id: 'demo_5',
    name: 'Hookah Lounge 78',
    latitude: 49.0002,
    longitude: 1.7128,
    address: '28 Boulevard des Cygnes',
    city: 'Mantes-la-Jolie',
    postal_code: '78200',
    phone: '+33 1 56 78 90 12',
    website: 'https://hookahlounge78.fr',
    price_range: '€€',
    average_rating: 4.6,
    review_count: 67,
    amenities: {
      wifi: true,
      parking: true,
      terrace: false,
      accessible: true,
      music: true,
      food: true
    },
    opening_hours: 'Lun-Dim: 17h-1h',
    photos: [],
    image: 'ChatGPT Image 2 janv. 2026, 14_45_06.png',
    description: 'Lounge moderne avec terrasse couverte et large choix de saveurs.',
    type: 'bar'
  },
  // --- Chichas fictives ajoutées ---
  {
    id: 6,
    osm_id: 'demo_6',
    name: 'Sahara Dream',
    latitude: 48.8700,
    longitude: 2.3500,
    address: '10 Rue du Désert',
    city: 'Paris',
    postal_code: '75010',
    phone: '+33 1 11 22 33 44',
    website: '',
    price_range: '€€',
    average_rating: 4.8,
    review_count: 51,
    amenities: { wifi: true, parking: false, terrace: true, accessible: true, music: true, food: false },
    opening_hours: 'Lun-Dim: 16h-2h',
    photos: ['https://images.unsplash.com/photo-1506744038136-46273834b3fb'],
    description: 'Ambiance orientale et cocktails signature.',
    type: 'bar'
  },
  {
    id: 7,
    osm_id: 'demo_7',
    name: 'Oasis Lounge',
    latitude: 48.8600,
    longitude: 2.3400,
    address: '22 Avenue du Palmier',
    city: 'Paris',
    postal_code: '75011',
    phone: '+33 1 22 33 44 55',
    website: '',
    price_range: '€',
    average_rating: 4.3,
    review_count: 23,
    amenities: { wifi: false, parking: true, terrace: true, accessible: false, music: true, food: true },
    opening_hours: 'Mar-Dim: 18h-1h',
    photos: ['https://images.unsplash.com/photo-1464983953574-0892a716854b'],
    description: 'Chicha lounge avec terrasse végétalisée.',
    type: 'bar'
  },
  {
    id: 8,
    osm_id: 'demo_8',
    name: 'Le Mirage',
    latitude: 48.8500,
    longitude: 2.3300,
    address: '5 Place du Sable',
    city: 'Paris',
    postal_code: '75012',
    phone: '+33 1 33 44 55 66',
    website: '',
    price_range: '€€€',
    average_rating: 4.9,
    review_count: 77,
    amenities: { wifi: true, parking: false, terrace: false, accessible: true, music: true, food: true },
    opening_hours: 'Jeu-Dim: 19h-3h',
    photos: ['https://images.unsplash.com/photo-1519125323398-675f0ddb6308'],
    description: 'Décor luxueux et ambiance feutrée.',
    type: 'bar'
  },
  {
    id: 9,
    osm_id: 'demo_9',
    name: 'Chicha Factory',
    latitude: 48.8400,
    longitude: 2.3200,
    address: '8 Rue de la Vapeur',
    city: 'Paris',
    postal_code: '75013',
    phone: '+33 1 44 55 66 77',
    website: '',
    price_range: '€€',
    average_rating: 4.1,
    review_count: 19,
    amenities: { wifi: true, parking: true, terrace: false, accessible: false, music: false, food: false },
    opening_hours: 'Ven-Sam: 20h-4h',
    photos: ['https://images.unsplash.com/photo-1504674900247-0877df9cc836'],
    description: 'Chicha industrielle et moderne.',
    type: 'bar'
  },
  {
    id: 10,
    osm_id: 'demo_10',
    name: 'Nuit d’Orient',
    latitude: 48.8300,
    longitude: 2.3100,
    address: '3 Rue des Mille et Une Nuits',
    city: 'Paris',
    postal_code: '75014',
    phone: '+33 1 55 66 77 88',
    website: '',
    price_range: '€€',
    average_rating: 4.4,
    review_count: 31,
    amenities: { wifi: false, parking: false, terrace: true, accessible: true, music: true, food: true },
    opening_hours: 'Lun-Dim: 17h-2h',
    photos: ['https://images.unsplash.com/photo-1465101046530-73398c7f28ca'],
    description: 'Ambiance Mille et Une Nuits.',
    type: 'bar'
  },
  {
    id: 11,
    osm_id: 'demo_11',
    name: 'Le Sultan',
    latitude: 48.8200,
    longitude: 2.3000,
    address: '7 Avenue du Sultan',
    city: 'Paris',
    postal_code: '75015',
    phone: '+33 1 66 77 88 99',
    website: '',
    price_range: '€€',
    average_rating: 4.0,
    review_count: 12,
    amenities: { wifi: true, parking: false, terrace: false, accessible: false, music: true, food: false },
    opening_hours: 'Ven-Sam: 18h-3h',
    photos: ['https://images.unsplash.com/photo-1503602642458-232111445657'],
    description: 'Chicha lounge à l’ambiance orientale.',
    type: 'bar'
  },
  {
    id: 12,
    osm_id: 'demo_12',
    name: 'Chicha Palace',
    latitude: 48.8100,
    longitude: 2.2900,
    address: '12 Rue du Palais',
    city: 'Paris',
    postal_code: '75016',
    phone: '+33 1 77 88 99 00',
    website: '',
    price_range: '€€€',
    average_rating: 4.6,
    review_count: 44,
    amenities: { wifi: true, parking: true, terrace: true, accessible: true, music: true, food: true },
    opening_hours: 'Lun-Dim: 15h-1h',
    photos: ['https://images.unsplash.com/photo-1465101178521-c1a9136a3b41'],
    description: 'Palais de la chicha, décor royal.',
    type: 'bar'
  },
  {
    id: 13,
    osm_id: 'demo_13',
    name: 'Le Patio',
    latitude: 48.8000,
    longitude: 2.2800,
    address: '18 Rue du Patio',
    city: 'Paris',
    postal_code: '75017',
    phone: '+33 1 88 99 00 11',
    website: '',
    price_range: '€',
    average_rating: 4.2,
    review_count: 21,
    amenities: { wifi: false, parking: true, terrace: true, accessible: true, music: false, food: true },
    opening_hours: 'Mar-Dim: 16h-0h',
    photos: ['https://images.unsplash.com/photo-1465101046530-73398c7f28ca'],
    description: 'Chicha lounge avec patio extérieur.',
    type: 'bar'
  },
  {
    id: 14,
    osm_id: 'demo_14',
    name: 'Le QG',
    latitude: 48.7900,
    longitude: 2.2700,
    address: '2 Rue du QG',
    city: 'Paris',
    postal_code: '75018',
    phone: '+33 1 99 00 11 22',
    website: '',
    price_range: '€€',
    average_rating: 4.5,
    review_count: 38,
    amenities: { wifi: true, parking: false, terrace: false, accessible: false, music: true, food: true },
    opening_hours: 'Lun-Dim: 18h-2h',
    photos: ['https://images.unsplash.com/photo-1506744038136-46273834b3fb'],
    description: 'Le QG des amateurs de chicha.',
    type: 'bar'
  },
  {
    id: 15,
    osm_id: 'demo_15',
    name: 'L’Atmosphère',
    latitude: 48.7800,
    longitude: 2.2600,
    address: '20 Rue de l’Atmosphère',
    city: 'Paris',
    postal_code: '75019',
    phone: '+33 1 00 11 22 33',
    website: '',
    price_range: '€',
    average_rating: 4.7,
    review_count: 29,
    amenities: { wifi: true, parking: true, terrace: true, accessible: true, music: true, food: false },
    opening_hours: 'Jeu-Dim: 19h-2h',
    photos: ['https://images.unsplash.com/photo-1519125323398-675f0ddb6308'],
    description: 'Ambiance cosy et moderne.',
    type: 'bar'
  }
];

// Initialize mock data in localStorage if not exists
export const initializeMockData = () => {
  if (typeof window !== 'undefined') {
    const existingData = localStorage.getItem('chichaAroundMeData');
    if (!existingData) {
      const initialData = {
        bars: mockBars,
        userChichas: [],
        reviews: [],
        userLists: [],
        listItems: [],
        users: []
      };
      localStorage.setItem('chichaAroundMeData', JSON.stringify(initialData));
      console.log('✅ Données de démonstration initialisées');
    }
  }
};
